### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by imirrori** [Lervaler/LEARN#2]
https://github.com/Lervaler/LEARN/blob/4a4ba2f5cff1922142db63f41bd4aea27b4d605f/04_dz/04_task_6/04_task_6/main.cpp#L3
Пробела перед < не хватает

https://github.com/Lervaler/LEARN/blob/4a4ba2f5cff1922142db63f41bd4aea27b4d605f/04_dz/04_task_6/04_task_6/main.cpp#L8
Перед [ не ставят пробела

https://github.com/Lervaler/LEARN/blob/4a4ba2f5cff1922142db63f41bd4aea27b4d605f/04_dz/04_task_6/04_task_6/main.cpp#L14
Не вижу что бы ch менялось. А это значит что ты используешь только первый элемент массива. Тогда зачем тебе массив?

https://github.com/Lervaler/LEARN/blob/4a4ba2f5cff1922142db63f41bd4aea27b4d605f/04_dz/04_task_6/04_task_6/main.cpp#L23
Сдвиги не правильные.

https://github.com/Lervaler/LEARN/blob/4a4ba2f5cff1922142db63f41bd4aea27b4d605f/04_dz/04_task_5/04_task_5/part1.cpp#L2
Пробельчиков богу пробельчиков

Начал смотреть, но очень много стилистических ошибок. Пройдись по dz4 и приведи все к одной стилитике.

**Comment by Lervaler** [comment]
- в дз 4 по пробелам прошлась,
- в задаче про скобки сделала без массива
- стилистические это тоже про пробелы или это про названия функций и слов?
п.с. тесты буду добавлять по мере готовности
